config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  constraints(proc { AuthStrategy.reverse_proxy_auth? }) do
    get 'login'  => 'reverse_proxy_sessions#new'
    post 'login' => 'reverse_proxy_sessions#create'
    delete 'logout' => 'reverse_proxy_sessions#destroy'

    resources :users, only: AuthStrategy.reverse_proxy_user_routes do
      resource :api_token, only: :update
    end
  end
  constraints(proc { AuthStrategy.local_auth? }) do
    get 'login'  => 'local_sessions#new'
    post 'login' => 'local_sessions#create'
    delete 'logout' => 'local_sessions#destroy'

    resources :users, only: AuthStrategy.local_user_routes do
      resource :api_token, only: :update
    end
  end

  resources :organizations do
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :machines, only: %i[create index new]
    resources :memberships, only: [:create]
    resource :organization_token, only: :update
    resources :relays, controller: 'docker_relays', only: [:index]
    resources :scan_schedules, only: %i[index create new], controller: :organization_scan_schedules
    resources :security_tests, controller: :organization_security_tests, only: %i[index create]
    resources :enforcements, controller: :organization_enforcements, only: [:create]
    resource :iaas_configuration, only: %i[show create]
    resources :ssh_key_pairs, only: %i[index create new]
    resources :result_export_queues, only: %i[new]
    resources :jira_export_queues, only: %i[new create]
    resources :infosec_export_queues, only: %i[new create]
    collection do
      post 'default'
    end
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  get '/machines/:id', to: redirect('/machines/%{id}/results?scan_id=latest')
  resources :machines, only: %i[edit update destroy] do
    resources :ping_connectivity_checks, only: %i[create show]
    resources :ssh_connectivity_checks, only: %i[create show]
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :scan_schedules, only: %i[create new], controller: :machine_scan_schedules
    resources :security_tests, controller: :machine_security_tests, only: %i[index create]
    resources :services, only: %i[index new create update edit]
    resources :service_discoveries, only: %i[index create]
    resource :ssh_key_pair_assignment, only: %i[create destroy]
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  resources :docker_commands, only: :destroy do
    resources :assessments, only: :index
  end
  resources :result_ignore_rules, only: :destroy
  resources :result_exporters, only: :create
  resources :security_container_configs, only: %i[show update destroy]
  resources :relays, controller: 'docker_relays', only: %i[update destroy]
  resources :repository_security_containers, only: :destroy
  resources :organization_configurations, only: [:update]
  resources :memberships, only: [:destroy]
  resources :user_profiles, only: [:update]
  resources :organization_scan_schedules, only: %i[update destroy edit]
  resources :machine_scan_schedules, only: %i[update destroy edit]
  resources :enforcements, controller: :organization_enforcements, only: [:destroy]
  resources :iaas_configurations, only: %i[show update] do
    resources :iaas_discoveries, only: :create
  end
  resources :services, only: %i[show destroy]
  resources :ssh_key_pairs, only: [:destroy]
  resources :notification_channels, only: :update
  resources :service_discoveries, only: :show
  resources :security_test_repositories, except: :edit do
    resources :repository_security_containers, only: %i[new create]
    resources :repository_whitelist_entries, only: %i[create destroy]
    resources :repository_members, only: :create
  end

  resources :repository_members, only: :destroy

  resources :requirement_groups, except: %i[edit] do
    resources :requirements, only: [:create]
  end
  resources :requirements, only: %i[edit update destroy] do
    resources :provisions, only: %i[index create]
  end
  resources :password_resets, only: %i[new create edit update], param: :provided_token
  resources :email_confirmations, only: :show, param: :email_confirmation_token
  resources :provisions, only: :destroy
  resources :jira_export_queues, only: %i[edit update destroy]
  resources :infosec_export_queues, only: %i[edit update destroy]

  root to: 'home#index'
end
# rubocop:enable BlockLength

app/controllers/machine_security_tests_controller.rb
# frozen_string_literal: true

class MachineSecurityTestsController < ApplicationController
  before_action :set_machine, only: %i[index create]
  layout 'machine', only: :index

  def index
    @org = @machine.organization
    @containers = OrganizationSecurityContainer.all_by_id(organization_id: @org.db_id)
  end

  def create
    requirement = params[:requirement].present? && params[:requirement] == 'true'
    @container_configs = SecurityContainerConfig.create_configs(@machine, container_ids, requirement)
  end

  private

  # Strong Parameters Helpers
  def container_ids
    params.require(:container_ids)
  end

  def set_machine
    @machine = Machine.find params[:machine_id]
  end
end

app/views/machine_security_tests/_enforcements.haml
.row
  .col-md-12
    .box.box-default
      .box-header.with-border
        %i.fa.fa-tasks
        %h3.box-title Organization Tests and Requirements
        .box-tools.pull-right
          %button.btn.btn-box-tool{ type: 'button', 'data-widget' => 'collapse' }
            %i.fa.fa-minus
      .box-body
        - enforcements = machine.organization.enforcements
        - org_sc_configs = machine.organization.security_container_configs
        .container-fluid
          - if enforcements.blank? && org_sc_configs.blank?
            .row
              .col-md-12
                %b Neither organization tests nor requirements are being enforced.
          - else
            .row
              .col-md-4
                %b
                  Requirement Group
            - machine.organization.enforcements.each do |enforcement|
              .row.req-group{ style: 'padding: 5px 0px;', 'data-enforcement' => enforcement.id }
                .col-md-4.req-group-name
                  %a.req-list-toggle{ href: '#', style: 'margin-right: 5px;' }
                    %i.fa.fa-plus-circle
                  = enforcement.requirement_group_name
              .row.req-list{ style: 'display: none;', 'data-enforcement' => enforcement.id }
                .col-md-12
                  = render 'requirements/requirements_list', target: machine, enforcement: enforcement, requirements: machine.organization.requirements
            - if org_sc_configs.present?
              .row.req-group{ style: 'padding: 5px 0px;' }
                .col-md-4.req-group-name
                  %a.req-list-toggle{ href: '#', style: 'margin-right: 5px;' }
                    %i.fa.fa-plus-circle
                  Organization Tests
              .row.req-list{ style: 'display: none;' }
                .col-md-12
                  = render 'requirements/organization_security_tests',
                    organization: machine.organization,
                    org_sc_configs: org_sc_configs,
                    config_ids: machine.security_container_configs.map(&:security_container_id).to_set

app/views/machine_security_tests/create.js.haml
- if @container_configs.present?
  - view = j(render(partial: 'security_tests/security_test_rows', locals: { configs: @container_configs }))
  :plain
    $('#enabled-containers').append("#{view}");

:plain
  $('select.select2').val(null).trigger('change');

- @container_configs.each do |cc|
  :ruby
    container_id = cc[:container].id.to_i
    parameters = "?container_ids%5B%5D=#{j(container_id.to_s)}"
  :plain
    $('a[href*="#{parameters}"]').text('Config Created').toggleClass('btn-success btn-default').addClass('disabled');
    $('.scan-machine').removeClass('disabled');
    $('.scan-machine').attr('title', 'Press to scan this machine.');

app/views/machine_security_tests/index.haml
- content_for :sidebar do
  = render 'sidebar', machine: @machine, org: @machine.organization

- content_for :header_content do
  = render 'assessable/header', machine: @machine, large_title: 'Security Tests'
  = render 'application/flash_messages'

- content_for :main_window_content do
  .row
    .col-md-12
      .box.box-default
        .box-header.with-border
          %h3.box-title
            %i.fa.fa-cubes
            Security Test Selection and Configuration
          .box-tools.pull-right
            .btn.btn-box-tool
              = render 'tooltip', message: 'Security Tests chosen here will only run on the selected machine.'
            %button.btn.btn-box-tool{ type: 'button', 'data-widget' => 'collapse' }
              %i.fa.fa-minus
        .box-body
          = render 'security_tests/security_tests', form_path: machine_security_tests_path(@machine.id), target: @machine, containers: @containers

  = render 'enforcements', machine: @machine
  = render 'result_ignore_rules/result_ignore_rules', rule_scope: 'machine', machine: @machine

- content_for :side_window_content do
  = render 'machines/machine_info', machine: @machine