config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  constraints(proc { AuthStrategy.reverse_proxy_auth? }) do
    get 'login'  => 'reverse_proxy_sessions#new'
    post 'login' => 'reverse_proxy_sessions#create'
    delete 'logout' => 'reverse_proxy_sessions#destroy'

    resources :users, only: AuthStrategy.reverse_proxy_user_routes do
      resource :api_token, only: :update
    end
  end
  constraints(proc { AuthStrategy.local_auth? }) do
    get 'login'  => 'local_sessions#new'
    post 'login' => 'local_sessions#create'
    delete 'logout' => 'local_sessions#destroy'

    resources :users, only: AuthStrategy.local_user_routes do
      resource :api_token, only: :update
    end
  end

  resources :organizations do
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :machines, only: %i[create index new]
    resources :memberships, only: [:create]
    resource :organization_token, only: :update
    resources :relays, controller: 'docker_relays', only: [:index]
    resources :scan_schedules, only: %i[index create new], controller: :organization_scan_schedules
    resources :security_tests, controller: :organization_security_tests, only: %i[index create]
    resources :enforcements, controller: :organization_enforcements, only: [:create]
    resource :iaas_configuration, only: %i[show create]
    resources :ssh_key_pairs, only: %i[index create new]
    resources :result_export_queues, only: %i[new]
    resources :jira_export_queues, only: %i[new create]
    resources :infosec_export_queues, only: %i[new create]
    collection do
      post 'default'
    end
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  get '/machines/:id', to: redirect('/machines/%{id}/results?scan_id=latest')
  resources :machines, only: %i[edit update destroy] do
    resources :ping_connectivity_checks, only: %i[create show]
    resources :ssh_connectivity_checks, only: %i[create show]
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :scan_schedules, only: %i[create new], controller: :machine_scan_schedules
    resources :security_tests, controller: :machine_security_tests, only: %i[index create]
    resources :services, only: %i[index new create update edit]
    resources :service_discoveries, only: %i[index create]
    resource :ssh_key_pair_assignment, only: %i[create destroy]
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  resources :docker_commands, only: :destroy do
    resources :assessments, only: :index
  end
  resources :result_ignore_rules, only: :destroy
  resources :result_exporters, only: :create
  resources :security_container_configs, only: %i[show update destroy]
  resources :relays, controller: 'docker_relays', only: %i[update destroy]
  resources :repository_security_containers, only: :destroy
  resources :organization_configurations, only: [:update]
  resources :memberships, only: [:destroy]
  resources :user_profiles, only: [:update]
  resources :organization_scan_schedules, only: %i[update destroy edit]
  resources :machine_scan_schedules, only: %i[update destroy edit]
  resources :enforcements, controller: :organization_enforcements, only: [:destroy]
  resources :iaas_configurations, only: %i[show update] do
    resources :iaas_discoveries, only: :create
  end
  resources :services, only: %i[show destroy]
  resources :ssh_key_pairs, only: [:destroy]
  resources :notification_channels, only: :update
  resources :service_discoveries, only: :show
  resources :security_test_repositories, except: :edit do
    resources :repository_security_containers, only: %i[new create]
    resources :repository_whitelist_entries, only: %i[create destroy]
    resources :repository_members, only: :create
  end

  resources :repository_members, only: :destroy

  resources :requirement_groups, except: %i[edit] do
    resources :requirements, only: [:create]
  end
  resources :requirements, only: %i[edit update destroy] do
    resources :provisions, only: %i[index create]
  end
  resources :password_resets, only: %i[new create edit update], param: :provided_token
  resources :email_confirmations, only: :show, param: :email_confirmation_token
  resources :provisions, only: :destroy
  resources :jira_export_queues, only: %i[edit update destroy]
  resources :infosec_export_queues, only: %i[edit update destroy]

  root to: 'home#index'
end
# rubocop:enable BlockLength

app/models/organization_scan_schedule.rb
# frozen_string_literal: true

class OrganizationScanSchedule < ScanSchedule
  belongs_to :organization
  collection_path 'organizations/:organization_id/scan_schedules'
  resource_path 'organization_scan_schedules/:id'
end

app/controllers/organization_scan_schedules_controller.rb
# frozen_string_literal: true

class OrganizationScanSchedulesController < ScanSchedulesController
  layout 'organization', only: :index

  def index
    @org = Organization.find params[:organization_id]
  end

  def new
    @schedule = OrganizationScanSchedule.new
  end

  def edit
    @schedule = OrganizationScanSchedule.find(params[:id])
  end

  def update
    schedule = OrganizationScanSchedule.new schedule_params_hash.merge(id: params[:id])
    flash[:danger] = 'Unable to update schedule.' unless schedule.save
  rescue NoradApiExceptions::NoradError
    flash[:danger] = 'Unable to update schedule.'
  ensure
    redirect_to organization_scan_schedules_path(params[:association_id])
  end

  def create
    org = Organization.new slug: params[:organization_id]
    flash[:danger] = 'Unable to create schedule.' unless org.scan_schedules.create(schedule_params_hash)
  rescue NoradApiExceptions::NoradError
    flash[:danger] = 'Unable to create schedule.'
  ensure
    redirect_to organization_scan_schedules_path(params[:association_id])
  end

  def destroy
    schedule = OrganizationScanSchedule.find(params[:id])
    flash[:danger] = 'Unable to remove schedule.' unless schedule.destroy
  rescue NoradApiExceptions::NoradError
    flash[:danger] = 'Unable to remove schedule.'
  ensure
    redirect_to organization_scan_schedules_path(params[:slug]), status: 303
  end

  private

  def schedule_params
    p = params[:organization_scan_schedule]
    p[:period] = p[:frequency].match?(/Daily/i) ? 'daily' : 'weekly'
    p[:at] = scan_timestamp(p)
    params.require(:organization_scan_schedule).permit(:at, :period)
  end

  def schedule_params_hash
    schedule_params.to_h
  end

  def scan_timestamp(p)
    offset = p[:am_pm] == 'PM' ? 12 : 0
    day = p[:frequency].match?(/Daily/i) ? '' : "#{p[:frequency]} "
    day + "#{p[:padded_hour].to_i + offset}:#{p[:padded_minute]}"
  end
end

app/views/organization_scan_schedules/edit.js.haml
:plain
  $('#scan-schedule-form-modal.modal.fade').html("#{j render(partial: 'scan_schedules/form', locals: { schedule: @schedule, association_id: params[:slug] })}")
  $('#scan-schedule-form-modal').modal('show')
  $('button#schedule-form-save-button').click(function(e) {
    e.preventDefault();
    $('form.schedule-form').submit();
  });

app/views/organization_scan_schedules/index.haml
- content_for :sidebar do
  = render 'sidebar', org: @org
-# Until the API truly supports multiple schedules, the UI should essentially treat this as a
  singular resource. The API enforces that only one schedule can be created for an organization,
  so for now it is safe to grab the first schedule that is returned.
- schedule = @org.scan_schedules.first || @org.scan_schedules.build
- can_modify = schedule.user_can_modify?(current_user, @org)
%section.content-header
  = render 'organization_header', org: @org, menu_name: 'Scan Schedule'
  %h1{ style: 'display: inline-block' }
  = render 'application/flash_messages'
%section.content
  .box.box-default
    .box-header.with-border
      %i.fa.fa-clock-o
      %h3.box-title
        Scan Schedule
      - if schedule.new? && can_modify
        .box-tools.pull-right
          = link_to new_organization_scan_schedule_path(@org, slug: @org.slug), title: 'Add New Scan Schedule', remote: true, class: 'btn btn-xs btn-box-tool', id: 'add-new-schedule' do
            Create Schedule
    .box-body
      - if schedule.new?
        %h4.text-center
          You have not set up a recurring scan for the machines in this organization.
        %p.text-center
          = link_to new_organization_scan_schedule_path(@org, slug: @org.slug), class: 'click-here-link', title: 'Add New Scan Schedule', remote: true do
            Click Here
          to add a recurring scan.
      - else
        :ruby
          edit_path = edit_organization_scan_schedule_path(schedule, slug: @org.slug)
          destroy_path = organization_scan_schedule_path(schedule, slug: @org.slug)
        = render partial: 'scan_schedules/table', locals: { schedule: schedule, edit_path: edit_path, destroy_path: destroy_path, can_modify: can_modify }
.modal.fade#scan-schedule-form-modal

app/views/organization_scan_schedules/new.js.haml
:plain
  $('#scan-schedule-form-modal.modal.fade').html("#{j render(partial: 'scan_schedules/form', locals: { schedule: @schedule, association_id: params[:slug] })}")
  $('#scan-schedule-form-modal').modal('show')
  $('button#schedule-form-save-button').click(function(e) {
    e.preventDefault();
    $('form.schedule-form').submit();
  });