config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  constraints(proc { AuthStrategy.reverse_proxy_auth? }) do
    get 'login'  => 'reverse_proxy_sessions#new'
    post 'login' => 'reverse_proxy_sessions#create'
    delete 'logout' => 'reverse_proxy_sessions#destroy'

    resources :users, only: AuthStrategy.reverse_proxy_user_routes do
      resource :api_token, only: :update
    end
  end
  constraints(proc { AuthStrategy.local_auth? }) do
    get 'login'  => 'local_sessions#new'
    post 'login' => 'local_sessions#create'
    delete 'logout' => 'local_sessions#destroy'

    resources :users, only: AuthStrategy.local_user_routes do
      resource :api_token, only: :update
    end
  end

  resources :organizations do
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :machines, only: %i[create index new]
    resources :memberships, only: [:create]
    resource :organization_token, only: :update
    resources :relays, controller: 'docker_relays', only: [:index]
    resources :scan_schedules, only: %i[index create new], controller: :organization_scan_schedules
    resources :security_tests, controller: :organization_security_tests, only: %i[index create]
    resources :enforcements, controller: :organization_enforcements, only: [:create]
    resource :iaas_configuration, only: %i[show create]
    resources :ssh_key_pairs, only: %i[index create new]
    resources :result_export_queues, only: %i[new]
    resources :jira_export_queues, only: %i[new create]
    resources :infosec_export_queues, only: %i[new create]
    collection do
      post 'default'
    end
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  get '/machines/:id', to: redirect('/machines/%{id}/results?scan_id=latest')
  resources :machines, only: %i[edit update destroy] do
    resources :ping_connectivity_checks, only: %i[create show]
    resources :ssh_connectivity_checks, only: %i[create show]
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :scan_schedules, only: %i[create new], controller: :machine_scan_schedules
    resources :security_tests, controller: :machine_security_tests, only: %i[index create]
    resources :services, only: %i[index new create update edit]
    resources :service_discoveries, only: %i[index create]
    resource :ssh_key_pair_assignment, only: %i[create destroy]
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  resources :docker_commands, only: :destroy do
    resources :assessments, only: :index
  end
  resources :result_ignore_rules, only: :destroy
  resources :result_exporters, only: :create
  resources :security_container_configs, only: %i[show update destroy]
  resources :relays, controller: 'docker_relays', only: %i[update destroy]
  resources :repository_security_containers, only: :destroy
  resources :organization_configurations, only: [:update]
  resources :memberships, only: [:destroy]
  resources :user_profiles, only: [:update]
  resources :organization_scan_schedules, only: %i[update destroy edit]
  resources :machine_scan_schedules, only: %i[update destroy edit]
  resources :enforcements, controller: :organization_enforcements, only: [:destroy]
  resources :iaas_configurations, only: %i[show update] do
    resources :iaas_discoveries, only: :create
  end
  resources :services, only: %i[show destroy]
  resources :ssh_key_pairs, only: [:destroy]
  resources :notification_channels, only: :update
  resources :service_discoveries, only: :show
  resources :security_test_repositories, except: :edit do
    resources :repository_security_containers, only: %i[new create]
    resources :repository_whitelist_entries, only: %i[create destroy]
    resources :repository_members, only: :create
  end

  resources :repository_members, only: :destroy

  resources :requirement_groups, except: %i[edit] do
    resources :requirements, only: [:create]
  end
  resources :requirements, only: %i[edit update destroy] do
    resources :provisions, only: %i[index create]
  end
  resources :password_resets, only: %i[new create edit update], param: :provided_token
  resources :email_confirmations, only: :show, param: :email_confirmation_token
  resources :provisions, only: :destroy
  resources :jira_export_queues, only: %i[edit update destroy]
  resources :infosec_export_queues, only: %i[edit update destroy]

  root to: 'home#index'
end
# rubocop:enable BlockLength

app/controllers/organization_security_tests_controller.rb
# frozen_string_literal: true

class OrganizationSecurityTestsController < ApplicationController
  layout 'organization', only: :index
  before_action :set_organization, only: %i[index create]

  def index
    @security_containers = OrganizationSecurityContainer.all_by_id(organization_id: @org.db_id)
    @container_configs = @org.security_container_configs
  end

  def create
    requirement = params[:requirement].present? && params[:requirement] == 'true'
    @container_configs = SecurityContainerConfig.create_configs(@org, container_ids, requirement)
  end

  private

  def set_organization
    @org = Organization.find params[:organization_id]
  end

  def container_ids
    params.require(:container_ids)
  end
end

app/views/organization_security_tests/_enforcements.haml
.container-fluid
  .row
    .col-sm-6.col-xs-6
      %b
        Requirement Group
    .col-sm-6.col-xs-3
      %b
        Actions
  - org.enforcements.each do |enforcement|
    .row.req-group{ style: 'padding: 5px 0px;', 'data-enforcement' => enforcement.id }
      .col-sm-6.col-xs-6.req-group-name
        %a.req-list-toggle{ href: '#', style: 'margin-right: 5px;' }
          %i.fa.fa-plus-circle
        = enforcement.requirement_group_name
      .col-sm-6.col-xs-3.req-group-actions
        :ruby
          classes = 'btn btn-xs btn-danger'
          disable_content = '<i class="fa fa-spinner fa-spin"></i>'
          confirm_msg = 'Are you sure you want to remove this requirement group?'
        = link_to 'Remove', enforcement_path(enforcement), class: classes, method: :delete, remote: true, data: { 'disable_with' => disable_content, confirm: confirm_msg }
    .row.req-list{ style: 'display: none;', 'data-enforcement' => enforcement.id }
      .col-md-12
        = render 'requirements/requirements_list', target: org, enforcement: enforcement, requirements: org.requirements

app/views/organization_security_tests/create.js.haml
- view = j(render(partial: 'security_tests/security_test_rows', locals: { configs: @container_configs })) unless @container_configs.empty?
:plain
  $('#enabled-containers').append("#{view}");
  $('select.select2').val(null).trigger('change');

- @container_configs.each do |cc|
  :ruby
    container_id = cc[:container].id.to_i
    parameters = "?container_ids%5B%5D=#{j(container_id.to_s)}"
  :plain
    $('a[href*="#{parameters}"]').text('Config Created').toggleClass('btn-success btn-default').addClass('disabled')

app/views/organization_security_tests/index.haml
- content_for :sidebar do
  = render 'sidebar', org: @org
%section.content-header
  = render 'organization_header', org: @org, menu_name: 'Security Tests'
  = render 'application/flash_messages'
%section.content
  .row
    .col-md-12
      .box.box-default
        .box-header.with-border
          %i.fa.fa-cubes
          %h3.box-title
            Security Test Selection and Configuration
          .box-tools.pull-right
            .btn.btn-box-tool
              - msg = 'Security tests chosen here will run on all machines within the organization.'
              %i.fa.fa-question-circle{ 'data-toggle': 'tooltip', title: msg, 'data-placement': 'left' }
            %button.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
              %i.fa.fa-minus
        .box-body
          - form_path = organization_security_tests_path(@org.id)
          = render 'security_tests/security_tests', form_path: form_path, target: @org, containers: @security_containers
  .row
    .col-md-12
      .box.box-default
        .box-header.with-border
          %i.fa.fa-tasks
          %h3.box-title
            Organization Requirements
        .box-body
          .container-fluid{ style: 'margin-bottom: 15px;' }
            .row
              .col-md-12
                = form_tag organization_enforcements_path(@org), method: 'post' do
                  %div{ style: 'width: 70%; display: inline-block;' }
                  .form-group.col-md-9.col-sm-7{ style: 'padding-left: 0px;' }
                    %select.req-group-list.form-control.select2.display-none{ multiple: 'multiple', name: 'requirement_group_ids[]', data: { placeholder: 'Select one or more requirement groups to enable' } }
                      - RequirementGroup.all.each do |req_group|
                        %option{ value: req_group.id }= req_group.name
                  .form-group
                    - spin_icon= '<i class="fa fa-spinner fa-spin"></i>'
                    %button.btn.btn-default#add-requirements{ type: 'submit', data: { disable_with: 'Adding Requirement...' } }
                      Add Requirements
          = render 'enforcements', org: @org
  = render 'result_ignore_rules/result_ignore_rules', rule_scope: 'organization', org: @org