config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  constraints(proc { AuthStrategy.reverse_proxy_auth? }) do
    get 'login'  => 'reverse_proxy_sessions#new'
    post 'login' => 'reverse_proxy_sessions#create'
    delete 'logout' => 'reverse_proxy_sessions#destroy'

    resources :users, only: AuthStrategy.reverse_proxy_user_routes do
      resource :api_token, only: :update
    end
  end
  constraints(proc { AuthStrategy.local_auth? }) do
    get 'login'  => 'local_sessions#new'
    post 'login' => 'local_sessions#create'
    delete 'logout' => 'local_sessions#destroy'

    resources :users, only: AuthStrategy.local_user_routes do
      resource :api_token, only: :update
    end
  end

  resources :organizations do
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :machines, only: %i[create index new]
    resources :memberships, only: [:create]
    resource :organization_token, only: :update
    resources :relays, controller: 'docker_relays', only: [:index]
    resources :scan_schedules, only: %i[index create new], controller: :organization_scan_schedules
    resources :security_tests, controller: :organization_security_tests, only: %i[index create]
    resources :enforcements, controller: :organization_enforcements, only: [:create]
    resource :iaas_configuration, only: %i[show create]
    resources :ssh_key_pairs, only: %i[index create new]
    resources :result_export_queues, only: %i[new]
    resources :jira_export_queues, only: %i[new create]
    resources :infosec_export_queues, only: %i[new create]
    collection do
      post 'default'
    end
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  get '/machines/:id', to: redirect('/machines/%{id}/results?scan_id=latest')
  resources :machines, only: %i[edit update destroy] do
    resources :ping_connectivity_checks, only: %i[create show]
    resources :ssh_connectivity_checks, only: %i[create show]
    resources :result_ignore_rules, only: %i[create edit update destroy]
    resources :scan_schedules, only: %i[create new], controller: :machine_scan_schedules
    resources :security_tests, controller: :machine_security_tests, only: %i[index create]
    resources :services, only: %i[index new create update edit]
    resources :service_discoveries, only: %i[index create]
    resource :ssh_key_pair_assignment, only: %i[create destroy]
    member do
      post 'scan'
      get 'results'
      get 'history'
      get 'settings'
    end
  end

  resources :docker_commands, only: :destroy do
    resources :assessments, only: :index
  end
  resources :result_ignore_rules, only: :destroy
  resources :result_exporters, only: :create
  resources :security_container_configs, only: %i[show update destroy]
  resources :relays, controller: 'docker_relays', only: %i[update destroy]
  resources :repository_security_containers, only: :destroy
  resources :organization_configurations, only: [:update]
  resources :memberships, only: [:destroy]
  resources :user_profiles, only: [:update]
  resources :organization_scan_schedules, only: %i[update destroy edit]
  resources :machine_scan_schedules, only: %i[update destroy edit]
  resources :enforcements, controller: :organization_enforcements, only: [:destroy]
  resources :iaas_configurations, only: %i[show update] do
    resources :iaas_discoveries, only: :create
  end
  resources :services, only: %i[show destroy]
  resources :ssh_key_pairs, only: [:destroy]
  resources :notification_channels, only: :update
  resources :service_discoveries, only: :show
  resources :security_test_repositories, except: :edit do
    resources :repository_security_containers, only: %i[new create]
    resources :repository_whitelist_entries, only: %i[create destroy]
    resources :repository_members, only: :create
  end

  resources :repository_members, only: :destroy

  resources :requirement_groups, except: %i[edit] do
    resources :requirements, only: [:create]
  end
  resources :requirements, only: %i[edit update destroy] do
    resources :provisions, only: %i[index create]
  end
  resources :password_resets, only: %i[new create edit update], param: :provided_token
  resources :email_confirmations, only: :show, param: :email_confirmation_token
  resources :provisions, only: :destroy
  resources :jira_export_queues, only: %i[edit update destroy]
  resources :infosec_export_queues, only: %i[edit update destroy]

  root to: 'home#index'
end
# rubocop:enable BlockLength

app/models/machine.rb
# frozen_string_literal: true

class Machine
  include Her::Model
  include PrettyErrors
  include Commandable

  collection_path 'organizations/:organization_id/machines'
  resource_path 'machines/:id'

  has_one :agent
  has_one :ssh_key_pair
  has_many :agent_commands
  has_many :docker_commands, inverse_of: :machine, class_name: 'MachineDockerCommand'
  has_many :assessments
  has_many :result_ignore_rules, inverse_of: :machine, class_name: 'MachineResultIgnoreRule'
  has_many :security_container_configs, inverse_of: :machine, class_name: 'MachineContainerConfig'
  has_many :scan_schedules, inverse_of: :machine, class_name: 'MachineScanSchedule'
  has_many :services
  has_many :service_discoveries
  has_many :ping_connectivity_checks
  has_many :ssh_connectivity_checks
  belongs_to :organization

  custom_post :scan

  def key_without_ssh_service?
    organization.organization_errors.any? do |e|
      e['type'] == 'KeyPairAssignmentWithoutSshServiceError' && e['errable_type'] == 'Machine' && e['errable_id'] == id
    end
  end

  def latest_service_discovery
    service_discoveries&.sort { |a, b| b.created_at <=> a.created_at }.first
  end

  def ssh_service_without_key?
    organization.organization_errors.any? do |e|
      e['type'] == 'SshServiceWithoutKeyPairAssignmentError' && e['errable_type'] == 'Machine' && e['errable_id'] == id
    end
  end

  def latest_docker_command
    @latest_docker_command ||= MachineDockerCommand.get(:latest, _machine_id: id)
  rescue NoradApiExceptions::NotFoundError
    nil
  end

  def latest_assessments
    return [] if latest_docker_command.nil?

    latest_docker_command.assessments
  rescue NoradApiExceptions::NotFoundError
    []
  end

  def assessments_by_docker_command_id(dcid)
    assessments.where(docker_command_id: dcid)
  end

  def assessments_summary
    MachineScanSummary.find(id).assessments_summary
  end

  def status
    get_status latest_assessment_stats
  end

  def can_scan_be_disabled?
    !security_tests_present?
  end

  def security_tests_present?
    security_tests_configured? || organization.security_tests_configured?
  end

  private

  def security_tests_configured?
    security_container_configs.present?
  end

  # rubocop:disable Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity
  def get_status(results)
    return 'default' if results.blank?

    if results[:failing].positive?
      'fail'
    elsif results[:warning].positive? || results[:erroring].positive?
      'warn'
    elsif results[:passing].positive?
      'pass'
    elsif results[:informing].positive?
      'info'
    else
      'default'
    end
  end
  # rubocop:enable Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity
end

app/controllers/machines_controller.rb
# frozen_string_literal: true

class MachinesController < ApplicationController
  layout 'machine', except: [:index]
  before_action :set_machine, only: %i[history results settings update edit]

  def index
    @org = Organization.where(include_assessment_summary: true).find(params[:organization_id])
  rescue NoradApiExceptions::ForbiddenError
    flash.now[:danger] = 'You do not have access to view these machines!'
    render :forbidden
  else
    render layout: 'organization'
  end

  def new
    @org = Organization.find params[:organization_id]
  end

  def edit; end

  def update
    @machine.assign_attributes(machine: machine_params_hash)
    @machine.save!
  rescue NoradApiExceptions::NoradError, Her::Errors::ResourceInvalid
    render status: :unprocessable_entity, json: { errors: @machine.pretty_errors.split('.').map(&:strip) }
  end

  def create
    begin
      @org = Organization.find params[:organization_id]
    rescue NoradApiExceptions::NotFoundError
      render status: :not_found, json: { errors: 'Organization ID not found' }
      return
    end

    @machine = @org.machines.create machine: machine_params_hash
    @machine.save!
  rescue Her::Errors::ResourceInvalid, NoradApiExceptions::NoradError
    render status: :unprocessable_entity, json: { errors: @machine.pretty_errors.split('.').map(&:strip) }
  end

  def destroy
    @machine_id = params[:id]
    Machine.destroy_existing(@machine_id)
  rescue Her::Errors::ResourceInvalid, NoradApiExceptions::NoradError
    render status: :unprocessable_entity, json: { errors: 'Error destroying machine' }
  end

  def scan
    scan_response = Machine.scan id: params[:id]
    if scan_response.response_errors.present?
      render(json: { errors: scan_response.pretty_errors }, status: :unprocessable_entity)
    else
      head :ok
    end
  rescue NoradApiExceptions::NoradError
    render(json: { errors: 'Error starting scan' }, status: :unprocessable_entity)
  end

  def history
    @latest_scan_id = @machine.assessments_summary.keys.map(&:to_i).max.to_s
  rescue NoradApiExceptions::ForbiddenError
    flash.now[:danger] = 'You do not have access to view this machine!'
    render :forbidden
  end

  def results
    set_docker_command_and_assessments
    @export_queues_present = @machine.organization.result_export_queues.present?
  rescue NoradApiExceptions::ForbiddenError
    flash.now[:danger] = 'You do not have access to view this machine!'
    render :forbidden
  end

  def settings
    set_new_service_modal
  rescue NoradApiExceptions::ForbiddenError
    flash.now[:danger] = 'You do not have access to view this machine!'
    render :forbidden
  end

  private

  def set_docker_command_and_assessments
    @scan_id = params[:scan_id].to_i

    if @scan_id.zero?
      @assessments = @machine.latest_assessments
      @docker_command = @machine.latest_docker_command
      return
    end

    @assessments = @machine.assessments_by_docker_command_id(@scan_id)
    @docker_command = DockerCommand.find(@scan_id)
  end

  def set_new_service_modal
    # rubocop:disable Style/SafeNavigation
    @render_new_service_modal = params[:render_new_service_modal] && params[:render_new_service_modal].match(/[Tt]rue/)
    # rubocop:enable Style/SafeNavigation
  end

  def redirect_to_machine_creation_success_page(machine)
    flash[:success] = 'Machine successfully created!'
    flash[:warning] = "Please add the services you'd like to test." if machine.services.blank?
    redirect_to machine_services_path(machine)
  end

  def redirect_to_machine_creation_error_page(organization)
    flash[:danger] = "Unable to create machine. #{@machine.pretty_errors}"
    redirect_to organization_machines_path(organization)
  end

  # Strong Parameters Helpers
  def machine_params
    params.require(:machine).permit(:ip, :fqdn, :description, :name, :use_fqdn_as_target)
  end

  def machine_params_hash
    machine_params.to_h
  end
  # End Strong Parameters Helpers

  def set_machine
    @machine = Machine.find params[:id]
    @org = @machine.organization
  end
end

app/helpers/machines_helper.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ModuleLength
module MachinesHelper
  require 'base64'

  STATUS_COLORS = {
    'pass' => 'success',
    'warn' => 'warning',
    'error' => 'warning',
    'fail' => 'danger',
    'info' => 'info'
  }.tap do |h|
    h.default = 'default'
  end.freeze

  STATUS_HEX_COLORS = {
    'pass' => '#00a65a',
    'warn' => '#f39c12',
    'error' => '#f39c12',
    'fail' => '#f56954',
    'info' => '#00c0ef'
  }.tap do |h|
    h.default = '#d2d6de'
  end.freeze

  STATUS_ICONS = {
    'pass' => 'fa-check-circle',
    'warn' => 'fa-exclamation-triangle',
    'error' => 'fa-exclamation-triangle',
    'fail' => 'fa-times-circle',
    'info' => 'fa-info-circle'
  }.tap do |h|
    h.default = 'fa-question-circle'
  end.freeze

  def assessments_unavailable?(docker_command_state, assessments)
    docker_command_state == 'pending' || docker_command_state == 'errored' || assessments.empty?
  end

  def show_fqdn_or_ip(machine)
    return machine.fqdn if machine.fqdn.present?
    machine.ip
  end

  def machine_status_color(machine)
    status_color machine.status
  end

  def status_color(status)
    STATUS_COLORS[status]
  end

  def status_hex_color(status)
    STATUS_HEX_COLORS[status]
  end

  def status_icon(status)
    STATUS_ICONS[status]
  end

  def decode64(key)
    Base64.decode64(key)
  end

  def assessments_grouped_by_reqs(assessments)
    initial = Hash.new do |a, k|
      a[k] = { status: '', assessments: [] }
    end
    assessments.each_with_object(initial) do |a, m|
      next m = add_assessment_to_group('ungrouped', -1, m, a) if a['associated_requirements'].empty?
      a['associated_requirements'].each do |r|
        m = add_assessment_to_group(r['name'], r['requirement_group_id'], m, a)
      end
    end
  end

  def add_assessment_to_group(key, gid, memo, assessment)
    memo[key][:assessments] << assessment
    memo[key][:status] = dominant_status(assessment_status(assessment), memo[key][:status])
    memo[key][:requirement_group_id] = gid
    memo
  end

  def security_container_completion_time_string(assessment)
    return '' unless assessment.state == 'complete'
    timestamp = format_timestamp(assessment.updated_at)
    "Completed on #{timestamp}"
  end

  def security_container_header_string(assessment)
    "#{assessment.repository_name}/#{title(assessment)} - v#{version(assessment)}"
  end

  def service_name(assessment)
    assessment.service_id ? "[#{assessment.service_name}]" : ''
  end

  def remove_scan_button(dc_id, commandable, opts = {})
    remove_scan_confirm_msg = 'Are you sure? This will permanently remove the scan and all its associated results!'
    link_to 'Remove',
            docker_command_path(dc_id, commandable.to_commandable_param_hash),
            data: { confirm: remove_scan_confirm_msg },
            class: opts[:classes],
            title: 'Remove Scan',
            method: :delete,
            remote: opts[:remote]
  end

  def scan_button_title(machine)
    if machine.security_tests_present?
      'Press to scan this machine.'
    else
      'Scanning not available until security tests have been added.'
    end
  end

  def scan_button_class_string(machine)
    if machine.security_tests_present?
      'btn btn-primary btn-xs pull-right'
    else
      'btn btn-primary btn-xs pull-right disabled'
    end
  end

  private

  # Assessment#title is essentially SecurityContainer#full_path; Reusing those helpers here
  def title(assessment)
    image_name container_name(assessment.title)
  end

  def version(assessment)
    tag_name container_name(assessment.title)
  end

  def link_to_scan_id(machine, latest_scan_id, scan_id)
    latest_or_scan_id = latest_scan_id == scan_id ? 'latest' : scan_id
    link_to(scan_id, results_machine_path(machine, scan_id: latest_or_scan_id))
  end
end
# rubocop:enable Metrics/ModuleLength

app/views/machines/_assessment_details.haml
- sorted_ignored_results = assessment.results.select(&:ignored).sort_by(&:status)
- sorted_unignored_results = assessment.results.reject(&:ignored).sort_by(&:status)
- if assessment.results.empty?
  %p No Results Available
- else
  .row{ style: 'margin-bottom: 15px;' }
    .col-md-6
      %b.underline Title
    .col-md-6
      %b.underline Actions
  = render partial: 'machines/results/result_row', collection: sorted_unignored_results, as: :result, locals: { machine: machine, org: org, show_terminal_output: false }

  .row.toggle-on-show-ignored{ class: ('hide' if sorted_ignored_results.count.zero?) }
    .col-md-12
      %i Not showing #{sorted_ignored_results.count} ignored #{'result'.pluralize(sorted_ignored_results.count)}

  %section.toggle-on-show-ignored.hide
    = render partial: 'machines/results/result_row', collection: sorted_ignored_results, as: :result, locals: { machine: machine, org: org }

app/views/machines/_machine_info.haml
.box.box-default#machine-info
  .box-header.with-border
    %h3.box-title
      %i.fa.fa-laptop
      Machine
    .box-tools.pull-right
      - if machine.security_tests_present?
        = link_to scan_machine_path(machine), class: "btn btn-xs btn-box-tool scan-machine", method: :post, remote: true, 'data-disable-with': 'Starting...' do
          %i.fa.fa-play-circle
          Scan
      - else
        %span{ 'data-toggle' => 'tooltip', title: 'You need to add tests before attempting to scan', 'data-placement' => 'top' }
          %a.btn.btn-xs.btn-box-tool.scan-machine.disabled
            %i.fa.fa-play-circle
            Scan
      %button.btn.btn-box-tool{ 'data-widget': 'collapse' }
        %i.fa.fa-minus
  .box-body
    %div
      %b
        Name:
    .machine-info-detail
      = render 'machines/no_services_indicator', machine: machine
      #{machine.name}
    %hr.info-spacer
    %div
      %b
        Scan Target:
      .pull-right
        %i.btn-box-tool.fa.fa-question-circle.help-icon{ 'data-toggle': 'tooltip', title: "The preferred scan target. Will be defaulted to the machine's IP, but it can be set to the FQDN as well if you like.", 'data-placement': 'top' }
    - if machine.ip.present? && machine.fqdn.present?
      .machine-info-detail.underline{ 'data-toggle': 'tooltip', 'data-html': 'true', title: "<div class='tooltip-container'><div><b>IP:</b></div> <div>#{h machine.ip}</div> <br /> <div><b>FQDN:</b></div> <div>#{h machine.fqdn}</div></div>", 'data-placement': 'top' }
        = machine.target_address
    - else
      .machine-info-detail= machine.target_address
    %hr.info-spacer
    %div
      %b
        Description:
    .machine-info-detail.text-left
      = render partial: 'application/truncated_description', locals: { description: machine.description, length: 100 }

app/views/machines/_new_form.haml
.modal-dialog
  .modal-content
    .modal-header
      New Machine
      %button.close{ 'data-dismiss': 'modal' }
        %span &times;
    .modal-body
      - path = organization_machines_path(org)
      - machine = Machine.build(organization_id: org.id, ip: nil, fqdn: nil, name: nil, description: nil, use_fqdn_as_target: nil)
      = form_for machine, url: path, html: { class: 'machine-new-form' } do |f|
        .form-group
          %label Machine IP
          = f.text_field :ip, class: 'form-control'
        .form-group
          %label Machine FQDN
          = f.text_field :fqdn, class: 'form-control'
        .checkbox
          %label
            = f.check_box :use_fqdn_as_target
            Use FQDN as Target
        .form-group#machine-name
          %label Machine Name
          %span.help-block A name will be generated for you if this field is left blank.
          = f.text_field :name, class: 'form-control', maxlength: 36
        .form-group
          %label Machine Description
          = f.text_area :description, class: 'form-control'
        .form-group
          %input{ type: 'text', hidden: true, name: 'organization_token', value: org.token }
    .modal-footer
      %button.btn.btn-default{ "data-dismiss": 'modal' } Close
      %button.btn.btn-primary#create-machine-submit-button Submit

app/views/machines/_no_services_indicator.haml
- if machine.services.blank?
  = link_to machine_services_path(machine) do
    %i.circle-warning.fa.fa-exclamation-triangle{ 'data-toggle' => 'tooltip', title: 'This machine lacks associated services, that is typically necessary in order for scans to properly run', 'data-placement' => 'right' }

app/views/machines/_service_container.haml
- results[:data].each do |service, assessment_result_hash|
  - assessment_result_hash.each do |assessment, result_array|
    .row.service-row
      .col-md-12
        .service-results-header
          = requirements_to_human_from_assessment(assessment)
          [#{service}] -- #{security_container_header_string(assessment)}
        .service-results
          - show_ignored = local_assigns.fetch(:show_ignored, false)
          = render partial: 'machines/results/result_row',
                   collection: result_array,
                   as: :result,
                   locals: { show_terminal_output: false, show_ignored: show_ignored, machine: machine, org: org }

app/views/machines/_settings_pane.haml
.box.box-solid.box-primary
  = render partial: 'machine_scan_schedules/settings_panel', locals: { machine: machine }

app/views/machines/_ssh_key_pair_form.haml
- if org.ssh_key_pairs.blank?
  .callout.callout-warning
    %h4
      %i.fa.fa-warning
      Warning!
    %p
      No Keys available to assign to this machine.
      Keys must first be uploaded to the organization before being assigned to a machine.
      %br
      Please visit the
      = link_to 'Organization Settings Page', settings_organization_path(org)
      to upload keys.
- else
  = form_tag machine_ssh_key_pair_assignment_path(machine), method: 'post', class: 'form-inline' do
    .form-group.col-md-4
      %select.ssh-key-pair-select.form-control{ name: 'ssh_key_pair_id', style: 'width: 100%;' }
        - org.ssh_key_pairs.each do |kp|
          %option{ value: kp.id }= kp.name
    = submit_tag 'Assign Key To Machine', class: 'btn btn-success', data: { disable_with: 'Assigning...' }

app/views/machines/_summary.haml
.row
  .col-md-3.col-sm-6.col-xs-12
    .info-box.info-box-sm
      %span.info-box-icon.bg-aqua
        %i.fa.fa-laptop
      .info-box-content
        %span.info-box-text
          Machines
        %span.info-box-number#machine-count
          = org.machine_count
  .col-md-3.col-sm-6.col-xs-12
    .info-box.info-box-sm
      %span.info-box-icon.bg-green
        %i.fa.fa-thumbs-o-up
      .info-box-content
        %span.info-box-text
          Passing
        %span.info-box-number
          = org.machine_assessment_summary['passing']
  .col-md-3.col-sm-6.col-xs-12
    .info-box.info-box-sm
      %span.info-box-icon.bg-yellow
        %i.fa.fa-exclamation-triangle
      .info-box-content
        %span.info-box-text
          Erroring / Warning
        %span.info-box-number
          = org.machine_assessment_summary['erroring'] + org.machine_assessment_summary['warning']
  .col-md-3.col-sm-6.col-xs-12
    .info-box.info-box-sm
      %span.info-box-icon.bg-red
        %i.fa.fa-thumbs-o-down
      .info-box-content
        %span.info-box-text
          Failing
        %span.info-box-number
          = org.machine_assessment_summary['failing']

app/views/machines/edit.js.haml
:plain
  $('#machine-edit-form-modal.modal.fade').html("#{j render(partial: 'edit_form')}")
  $('#machine-edit-form-modal').modal('show')
  $('button#machine-edit-form-save-button').click(function(e) {
    e.preventDefault();
    $('form.machine-edit-form').submit();
  });

app/views/machines/forbidden.haml
- content_for :sidebar do
  = render 'sidebar', org: nil
%section.content-header
  %h1{ style: 'display: inline-block' }
    %span{ style: 'color: gray;' }
      Machine
%section.content
  - unless flash.keys.empty?
    - flash.each do |key, val|
      .callout{ class: "alert-#{key}" }
        %b= val

app/views/machines/history.haml
- content_for :sidebar do
  = render 'sidebar', org: @machine.organization, machine: @machine

- content_for :header_content do
  = render 'assessable/header', machine: @machine, large_title: "Scan History for Machine #{@machine.name}"
  = render 'application/flash_messages'

- content_for :main_window_content do
  #history-pane
    = render 'history_pane',
      machine: @machine,
      assessments_summary: @machine.assessments_summary,
      latest_scan_id: @latest_scan_id

- content_for :side_window_content do
  = render 'machines/machine_info', machine: @machine

app/views/machines/new.js.haml
- if @org
  :plain
    $('#machine-form-modal.modal.fade').html("#{j render(partial: 'new_form', locals: { org: @org })}")
    $('body').trigger({ type: 'machine_new_form', form_type: 'new' })
- else
  :plain
    Norad.alert('Error!', 'Unable to show the new machine creation form.', 'danger');

app/views/machines/results.haml
- content_for :sidebar do
  = render 'sidebar', org: @machine.organization, machine: @machine

- content_for :header_content do
  - small_title = format_timestamp(@assessments.map(&:created_at).max)
  = render 'assessable/header',
           machine: @machine,
           large_title: results_page_title(@scan_id, @assessments),
           small_title: small_title
  = render 'application/flash_messages', self_destructable: true

- content_for :main_window_content do
  - if @assessments.empty? && @docker_command&.state_details.present?
    .alert.alert-danger
      %p= @docker_command.state_details
  - else
    .box.box-default
      .box-header.with-border
        %h3.box-title
          %i.fa.fa-bar-chart
          Results
        %span.pull-right
          %strong.small{ style: 'margin-right: 10px;' }
            Grouped By:
          %span.btn-group.btn-group-xs{ 'data-toggle': 'buttons' }
            %label.btn.btn-primary.active
              %input.group-by-button{ type: 'radio', name: 'options', autocomplete: 'off', 'data-results-target': '.status-view', checked: '' } Status
            %label.btn.btn-primary
              %input.group-by-button{ type: 'radio', name: 'options', autocomplete: 'off', 'data-results-target': '.security-test-view' } Security Test
            %label.btn.btn-primary
              %input.group-by-button{ type: 'radio', name: 'options', autocomplete: 'off', 'data-results-target': '.requirement-view' } Requirement
          - unless total_ignored_for_assessments(@assessments).zero?
            %a.btn.btn-default.btn-xs.show-hide-ignored{ href: '#', 'data-toggle': 'button' } Show Ignored
      .box-body
        .row
          .col-md-12.result-views
            = render 'machines/results/status_view', docker_command_state: @docker_command&.state, assessments: @assessments, machine: @machine, org: @machine.organization
            = render 'machines/results/security_test_view', docker_command_state: @docker_command&.state, assessments: @assessments, machine: @machine, org: @machine.organization
            = render 'machines/results/requirement_view', docker_command_state: @docker_command&.state, assessments: @assessments, machine: @machine, org: @machine.organization

- content_for :side_window_content do
  = render 'machine_info', machine: @machine
  = render 'machines/results/stats', summary_stats: Assessment.statistics(@assessments)

app/views/machines/scan.js.haml
- if !@error_msg.nil?
  :plain
    Norad.alert('Failure', "#{ j(@error_msg) }", 'danger');
- else
  :plain
    Norad.alert('Success', "Scan started", 'success');